pub(crate) mod dylib {
    #[link(name = "cvAutoTrack", kind = "raw-dylib")]
    extern "C" {
        /* automatically generated by rust-bindgen 0.69.1 */
        pub fn verison(versionBuff: *mut ::std::os::raw::c_char) -> bool;
        pub fn init() -> bool;
        pub fn uninit() -> bool;
        pub fn startServe() -> bool;
        pub fn stopServe() -> bool;
        pub fn SetUseBitbltCaptureMode() -> bool;
        pub fn SetUseDx11CaptureMode() -> bool;
        pub fn SetHandle(handle: ::std::os::raw::c_longlong) -> bool;
        pub fn SetWorldCenter(x: f64, y: f64) -> bool;
        pub fn SetWorldScale(scale: f64) -> bool;
        pub fn ImportMapBlock(
            id_x: ::std::os::raw::c_int,
            id_y: ::std::os::raw::c_int,
            image_data: *const ::std::os::raw::c_char,
            image_data_size: ::std::os::raw::c_int,
            image_width: ::std::os::raw::c_int,
            image_height: ::std::os::raw::c_int,
        ) -> bool;
        pub fn ImportMapBlockCenter(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int) -> bool;
        pub fn ImportMapBlockCenterScale(
            x: ::std::os::raw::c_int,
            y: ::std::os::raw::c_int,
            scale: f64,
        ) -> bool;
        pub fn GetTransformOfMap(
            x: *mut f64,
            y: *mut f64,
            a: *mut f64,
            mapId: *mut ::std::os::raw::c_int,
        ) -> bool;
        pub fn GetPositionOfMap(x: *mut f64, y: *mut f64, mapId: *mut ::std::os::raw::c_int) -> bool;
        pub fn GetDirection(a: *mut f64) -> bool;
        pub fn GetRotation(a: *mut f64) -> bool;
        pub fn GetStar(x: *mut f64, y: *mut f64, isEnd: *mut bool) -> bool;
        pub fn GetStarJson(jsonBuff: *mut ::std::os::raw::c_char) -> bool;
        pub fn GetUID(uid: *mut ::std::os::raw::c_int) -> bool;
        pub fn GetAllInfo(
            x: *mut f64,
            y: *mut f64,
            mapId: *mut ::std::os::raw::c_int,
            a: *mut f64,
            r: *mut f64,
            uid: *mut ::std::os::raw::c_int,
        ) -> bool;
        pub fn GetInfoLoadPicture(
            path: *mut ::std::os::raw::c_char,
            uid: *mut ::std::os::raw::c_int,
            x: *mut f64,
            y: *mut f64,
            a: *mut f64,
        ) -> bool;
        pub fn GetInfoLoadVideo(
            path: *mut ::std::os::raw::c_char,
            pathOutFile: *mut ::std::os::raw::c_char,
        ) -> bool;
        pub fn DebugCapture() -> bool;
        pub fn DebugCapturePath(
            path_buff: *const ::std::os::raw::c_char,
            buff_size: ::std::os::raw::c_int,
        ) -> bool;
        pub fn GetLastErr() -> ::std::os::raw::c_int;
        pub fn GetLastErrMsg(
            msg_buff: *mut ::std::os::raw::c_char,
            buff_size: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int;
        pub fn GetLastErrJson(
            json_buff: *mut ::std::os::raw::c_char,
            buff_size: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int;
        pub fn SetDisableFileLog() -> bool;
        pub fn SetEnableFileLog() -> bool;
        pub fn GetCompileVersion(
            version_buff: *mut ::std::os::raw::c_char,
            buff_size: ::std::os::raw::c_int,
        ) -> bool;
        pub fn GetCompileTime(
            time_buff: *mut ::std::os::raw::c_char,
            buff_size: ::std::os::raw::c_int,
        ) -> bool;
        #[doc = " <summary>\n whether map image resources are embedded in dll\n </summary>\n <returns>true or false</returns>"]
        pub fn GetMapIsEmbedded() -> bool;
    }
}