on:
  workflow_call:
    inputs:
      rust-version:
        type: string
        required: false
        default: stable

jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        continue-on-error: false
      - name: Test
        run: cargo test