name: Continuous integration

on: [push]

jobs:
  check:
    name: Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      # 3. Set up cargo cache
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        continue-on-error: false
      - run: cargo check